from datetime import date, datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class Priority(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"
    urgent = "urgent"


class RequestStatus(str, Enum):
    open = "open"
    awaiting_assignment = "awaiting_assignment"
    assigned = "assigned"
    in_progress = "in_progress"
    resolved = "resolved"
    scheduled = "scheduled"
    completed = "completed"
    closed = "closed"
    cancelled = "cancelled"
    pending = "pending"
    waiting_for_approval = "waiting_for_approval"


class Tenant(BaseModel):
    tenant_id: str
    name: str
    email: str
    phone: str
    unit_id: str
    lease_status: str
    move_in_date: date


class Unit(BaseModel):
    unit_id: str
    property_name: str
    building: str
    floor: int
    unit_number: str
    property_type: str
    location: str
    status: str


class MaintenanceRequest(BaseModel):
    request_id: str
    tenant_id: str
    unit_id: str
    category: str
    description: str
    priority: Priority
    status: RequestStatus
    created_at: datetime
    updated_at: datetime | None = None
    assigned_team: str


class Payment(BaseModel):
    tenant_id: str
    billing_month: str
    amount: float
    payment_status: Literal["paid", "due", "overdue"]
    due_date: date
    paid_at: date | None = None


class TenantResolution(BaseModel):
    """Validated final response generated by the Stage 1 LangChain agent."""

    tenant_id: str = Field(description="PropCare tenant ID involved in the request")
    request_id: str | None = Field(default=None, description="New or relevant request ID")
    issue_category: str = Field(description="Operational category such as HVAC or plumbing")
    priority: Priority = Field(description="Assessed urgency")
    assigned_team: str = Field(description="Team responsible for next steps")
    action_taken: str = Field(description="Concrete action completed in this interaction")
    approval_required: bool = Field(description="Whether manager approval is needed")
    status: RequestStatus = Field(description="Current request status")
    summary: str = Field(description="Brief, resident-friendly summary")


class SupportMessage(BaseModel):
    tenant_id: str | None = None
    message: str = Field(min_length=3, max_length=2000)


class LoginRequest(BaseModel):
    email: str
    password: str
    role: Literal["tenant", "admin"]


class DemoSession(BaseModel):
    token: str
    role: Literal["tenant", "admin"]
    name: str
    tenant_id: str | None = None


class DemoCredentials(BaseModel):
    email: str
    password: str


class AdminOverview(BaseModel):
    open_requests: int
    urgent_issues: int
    active_units: int
    pending_approvals: int
    recent_activity: list[str]


class Stage2Message(BaseModel):
    message: str = Field(min_length=3, max_length=2000)
    thread_id: str | None = None


class ApprovalDecision(BaseModel):
    decision: Literal["approve", "reject", "edit"]
    approved_credit: float | None = Field(default=None, gt=0)
    note: str | None = None


class AssignmentUpdate(BaseModel):
    assigned_team: str
    status: RequestStatus
